const initialState = {
  actionList: {},
  carrierCode: 'dhlpaket',
  checkoutData: {},
  commentsBefore: [],
  commentsAfter: [],
  displayColor: '',
  errorMessage: '',
  footnotes: [],
  image: '',
  imageWidth: '',
  lastCarrierCode: '',
  lastDataHash: 0,
  loader: false,
  locations: {},
  methodCode: 'bestway',
  search: false,
  selectedLocation: null,
  selections: {},
  shippingSettingsController: true,
  title: '',
  visible: false,
};

export default initialState;
